import { Product, Category } from "./types";

export const categories: Category[] = [
  { id: "electronics", name: "Electronics", icon: "💻" },
  { id: "fashion", name: "Fashion", icon: "👔" },
  { id: "home", name: "Home & Kitchen", icon: "🏠" },
  { id: "beauty", name: "Beauty", icon: "✨" },
  { id: "sports", name: "Sports", icon: "⚽" },
  { id: "books", name: "Books", icon: "📚" },
  { id: "toys", name: "Toys & Games", icon: "🎮" },
  { id: "automotive", name: "Automotive", icon: "🚗" },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Noise-Cancelling Headphones",
    description: "Experience pure audio bliss with our flagship wireless headphones. Featuring advanced ANC technology, 40-hour battery life, and luxurious memory foam ear cushions.",
    price: 349.99,
    discount: 15,
    category: "electronics",
    brand: "AudioLux",
    stock: 45,
    rating: 4.8,
    reviewCount: 2341,
    images: ["/placeholder.svg"],
  },
  {
    id: "2",
    name: "Ultra-Slim 4K OLED Smart TV 65\"",
    description: "Stunning 4K OLED display with Dolby Vision, HDR10+, and built-in streaming. Razor-thin design with invisible bezels.",
    price: 1899.99,
    discount: 20,
    category: "electronics",
    brand: "VisionPro",
    stock: 12,
    rating: 4.9,
    reviewCount: 876,
    images: ["/placeholder.svg"],
  },
  {
    id: "3",
    name: "Italian Leather Messenger Bag",
    description: "Handcrafted from premium Italian full-grain leather. Features multiple compartments, padded laptop sleeve, and adjustable strap.",
    price: 289.99,
    discount: 0,
    category: "fashion",
    brand: "Artisan & Co",
    stock: 30,
    rating: 4.7,
    reviewCount: 543,
    images: ["/placeholder.svg"],
  },
  {
    id: "4",
    name: "Smart Home Hub Pro",
    description: "Control your entire home ecosystem from one elegant device. Compatible with 500+ smart devices, voice control, and touch display.",
    price: 199.99,
    discount: 10,
    category: "electronics",
    brand: "HomeSphere",
    stock: 78,
    rating: 4.5,
    reviewCount: 1205,
    images: ["/placeholder.svg"],
  },
  {
    id: "5",
    name: "Professional Chef's Knife Set",
    description: "8-piece Japanese Damascus steel knife set with walnut magnetic block. Each blade hand-forged by master craftsmen.",
    price: 449.99,
    discount: 25,
    category: "home",
    brand: "Blade & Soul",
    stock: 20,
    rating: 4.9,
    reviewCount: 389,
    images: ["/placeholder.svg"],
  },
  {
    id: "6",
    name: "Luxury Skincare Collection",
    description: "Complete skincare ritual with cleanser, serum, moisturizer, and eye cream. Infused with gold particles and hyaluronic acid.",
    price: 175.00,
    discount: 0,
    category: "beauty",
    brand: "Ethereal",
    stock: 55,
    rating: 4.6,
    reviewCount: 721,
    images: ["/placeholder.svg"],
  },
  {
    id: "7",
    name: "Carbon Fiber Road Bike",
    description: "Ultra-lightweight carbon frame with Shimano Ultegra groupset. Aerodynamic design for peak performance.",
    price: 2499.99,
    discount: 10,
    category: "sports",
    brand: "VeloElite",
    stock: 8,
    rating: 4.8,
    reviewCount: 156,
    images: ["/placeholder.svg"],
  },
  {
    id: "8",
    name: "Limited Edition Hardcover Collection",
    description: "Beautifully bound 5-book collection of classic literature with gold-leaf pages and ribbon bookmarks.",
    price: 129.99,
    discount: 0,
    category: "books",
    brand: "Heritage Press",
    stock: 40,
    rating: 4.7,
    reviewCount: 234,
    images: ["/placeholder.svg"],
  },
  {
    id: "9",
    name: "Mechanical Gaming Keyboard RGB",
    description: "Hot-swappable switches, per-key RGB, aircraft-grade aluminum frame. Built for champions.",
    price: 179.99,
    discount: 15,
    category: "electronics",
    brand: "KeyForge",
    stock: 63,
    rating: 4.6,
    reviewCount: 1892,
    images: ["/placeholder.svg"],
  },
  {
    id: "10",
    name: "Cashmere Blend Overcoat",
    description: "Timeless double-breasted overcoat in premium cashmere-wool blend. Tailored silhouette with satin lining.",
    price: 599.99,
    discount: 30,
    category: "fashion",
    brand: "Maison Noir",
    stock: 15,
    rating: 4.9,
    reviewCount: 98,
    images: ["/placeholder.svg"],
  },
  {
    id: "11",
    name: "Espresso Machine Titanium",
    description: "Dual boiler espresso machine with PID temperature control, integrated grinder, and steam wand.",
    price: 899.99,
    discount: 5,
    category: "home",
    brand: "BrewCraft",
    stock: 22,
    rating: 4.8,
    reviewCount: 445,
    images: ["/placeholder.svg"],
  },
  {
    id: "12",
    name: "RC Racing Drone 4K",
    description: "Professional racing drone with 4K camera, obstacle avoidance, and 30-minute flight time.",
    price: 699.99,
    discount: 12,
    category: "toys",
    brand: "SkyPilot",
    stock: 18,
    rating: 4.4,
    reviewCount: 312,
    images: ["/placeholder.svg"],
  },
];
